### ISSUE TITLE
QT5DIR env-var is necessary

### ISSUE THREAD

**Issue by MikeMitterer** [ArthurSonzogni/cmake-Qt5-example#1]
Thanks for your sample.
In my case I had to set an environment-var: QT5DIR and I had to set CMAKE_PREFIX_PATH with this var.

Below is my CMakeList.txt - I'm new to CMAKE/QT and maybe my problem is not generally relevant but if so - please add my patch to your documentation.

``` cmake
# ┌──────────────────────────────────────────────────────────────────┐
# │  Projects Settings                                               │
# └──────────────────────────────────────────────────────────────────┘

cmake_minimum_required(VERSION 2.8.12)
project(myApplication)

# ┌──────────────────────────────────────────────────────────────────┐
# │  Qt                                                              │
# └──────────────────────────────────────────────────────────────────┘

if (DEFINED ENV{QT5DIR})
    set(CMAKE_PREFIX_PATH $ENV{QT5DIR} ${CMAKE_PREFIX_PATH})
else ()
    message (FATAL_ERROR "ERROR: Environment variable QT5DIR is not set. Please locate your Qt folder MY_QT5_DIR.")
endif ()


set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_AUTOMOC ON)
find_package(Qt5Widgets REQUIRED)

# ┌──────────────────────────────────────────────────────────────────┐
# │  Source file                                                     │
# └──────────────────────────────────────────────────────────────────┘

file(GLOB_RECURSE source src/*.cpp)
include_directories(src)

# ┌──────────────────────────────────────────────────────────────────┐
# │  Applications  (entry points)                                    │ 
# └──────────────────────────────────────────────────────────────────┘

# FractalCreation
add_executable(myApplication app/myApplication.cpp ${source})
qt5_use_modules(myApplication Widgets)
```

**Comment by ArthurSonzogni** [comment]
Hi, thank you for you contribution !

I don't have to define this variable on linux and windows on my computer.
Can you provide more informations ?
- Operating system (windows, linux, ...)
- compiler
- how do you invoke cmake ? (cmake, cmake-gui, IDE like qtCreator, ... ?)

On windows, cmake cannot found by itself Qt libraries and ask us its locations, maybe it is just things like this.

**Comment by MikeMitterer** [comment]
I'm using CLion on Mac 10.9.5 
QT5DIR=/usr/local/Cellar/qt5/5.4.2

As you see - I'm using QT 5.4.2 - I think they changed the "modularity" somehow - maybe this caused my problem...

Toolchain:
![screenshot-1828](https://cloud.githubusercontent.com/assets/116654/9107104/1b028380-3c25-11e5-81f1-5c16a496609d.png)

**Comment by MikeMitterer** [comment]
I updated to CLion 1.1 and now with 1.1 it works without defining den env-var.

**Comment by ArthurSonzogni** [comment]
Thank you for your additional informations.
